# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c19d83d8152023c111af76fd84951296"
name = "reel-cart-app"
application_url = "https://tribunal-liz-deck-hospitals.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_files,read_files,write_content,read_content"

[auth]
redirect_urls = [
  "https://tribunal-liz-deck-hospitals.trycloudflare.com/auth/callback"
]

[app_proxy]
url = "https://tribunal-liz-deck-hospitals.trycloudflare.com/app/proxy"
subpath = "reel-data"
prefix = "apps"
